### ISSUE TITLE
Overly large xmlData query parameter for POST requests.

### ISSUE THREAD

**Issue by jwhayman** [humantech/zoho-recruit-api#2]
Hi there. I've had a bit of an issue with one client I'm using this library for. They have huge forms, so when someone submits a lot of data using the addRecord endpoint, they receive a 414 Request URI too long error because the xmlData query parameter is being included in the request url, not the POST body.

I've modified the addRecords function to prevent the xmlData parameter being sent in the URL, and to send it in the body of the POST request instead. Perhaps the xmlData should always be sent in the POST body for any request using it? This would allow for larger forms to be submitted without the potential of receiving the 414 error.

**Comment by perk11** [comment]
Also experiencing this.
